field_mapper_node:
  ros__parameters:
    input_topic_name: /main_battery
    input_message_type: sensor_msgs/msg/BatteryState
    output_topic_name: /battery_overlay
    output_message_type: wifi_viz/msg/MinMaxCurr
    field_mappings:
      - "voltage:current"
    static_fields:
      - "min=0.0"
      - "max=45.0"